-- OrderStatus v2: remove PACKED/SENT/RETURNED, add IN_COURIER
ALTER TABLE `order` MODIFY `status` VARCHAR(20) NOT NULL DEFAULT 'PENDING';
UPDATE `order` SET `status` = 'IN_COURIER' WHERE `status` IN ('PACKED', 'SENT');
UPDATE `order` SET `status` = 'CANCELLED' WHERE `status` = 'RETURNED';
ALTER TABLE `order` MODIFY `status` ENUM('PENDING', 'CONFIRMED', 'IN_COURIER', 'SHIPPED', 'DELIVERED', 'CANCELLED') NOT NULL DEFAULT 'PENDING';